// Code generated by protoc-gen-go.
// source: github.com/micro/kv-srv/proto/kv.proto
// DO NOT EDIT!

/*
Package go_micro_srv_kv is a generated protocol buffer package.

It is generated from these files:
	github.com/micro/kv-srv/proto/kv.proto

It has these top-level messages:
	Item
	GetRequest
	GetResponse
	PutRequest
	PutResponse
	DelRequest
	DelResponse
*/
package go_micro_srv_kv

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Item struct {
	Key        string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value      []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expiration int64  `protobuf:"varint,3,opt,name=expiration" json:"expiration,omitempty"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetResponse struct {
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetResponse) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type PutRequest struct {
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type PutResponse struct {
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type DelRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *DelRequest) Reset()                    { *m = DelRequest{} }
func (m *DelRequest) String() string            { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()               {}
func (*DelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type DelResponse struct {
}

func (m *DelResponse) Reset()                    { *m = DelResponse{} }
func (m *DelResponse) String() string            { return proto.CompactTextString(m) }
func (*DelResponse) ProtoMessage()               {}
func (*DelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*Item)(nil), "go.micro.srv.kv.Item")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.kv.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "go.micro.srv.kv.GetResponse")
	proto.RegisterType((*PutRequest)(nil), "go.micro.srv.kv.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "go.micro.srv.kv.PutResponse")
	proto.RegisterType((*DelRequest)(nil), "go.micro.srv.kv.DelRequest")
	proto.RegisterType((*DelResponse)(nil), "go.micro.srv.kv.DelResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for KV service

type KVClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...client.CallOption) (*PutResponse, error)
	Del(ctx context.Context, in *DelRequest, opts ...client.CallOption) (*DelResponse, error)
}

type kVClient struct {
	c           client.Client
	serviceName string
}

func NewKVClient(serviceName string, c client.Client) KVClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.kv"
	}
	return &kVClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *kVClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "KV.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Put(ctx context.Context, in *PutRequest, opts ...client.CallOption) (*PutResponse, error) {
	req := c.c.NewRequest(c.serviceName, "KV.Put", in)
	out := new(PutResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVClient) Del(ctx context.Context, in *DelRequest, opts ...client.CallOption) (*DelResponse, error) {
	req := c.c.NewRequest(c.serviceName, "KV.Del", in)
	out := new(DelResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KV service

type KVHandler interface {
	Get(context.Context, *GetRequest, *GetResponse) error
	Put(context.Context, *PutRequest, *PutResponse) error
	Del(context.Context, *DelRequest, *DelResponse) error
}

func RegisterKVHandler(s server.Server, hdlr KVHandler) {
	s.Handle(s.NewHandler(&KV{hdlr}))
}

type KV struct {
	KVHandler
}

func (h *KV) Get(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.KVHandler.Get(ctx, in, out)
}

func (h *KV) Put(ctx context.Context, in *PutRequest, out *PutResponse) error {
	return h.KVHandler.Put(ctx, in, out)
}

func (h *KV) Del(ctx context.Context, in *DelRequest, out *DelResponse) error {
	return h.KVHandler.Del(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x77, 0xb7, 0xab, 0xe0, 0x54, 0x51, 0x82, 0x42, 0x51, 0x11, 0xc9, 0x41, 0xf4, 0x60,
	0x0a, 0xeb, 0x41, 0xcf, 0x22, 0x88, 0x08, 0x22, 0x39, 0x78, 0xdf, 0x5d, 0x86, 0x35, 0x74, 0xbb,
	0xa9, 0x6d, 0x5a, 0xf4, 0x2d, 0x7d, 0x24, 0x27, 0x53, 0xb1, 0xc5, 0x8d, 0x07, 0x6f, 0x49, 0xfe,
	0x99, 0x6f, 0xbe, 0x81, 0xc0, 0xd9, 0xc2, 0xb8, 0xd7, 0x7a, 0xa6, 0xe6, 0x36, 0x4f, 0x73, 0x33,
	0x2f, 0x6d, 0x9a, 0x35, 0x97, 0x55, 0xd9, 0xa4, 0x45, 0x69, 0x9d, 0xbf, 0x28, 0x3e, 0x88, 0xdd,
	0x85, 0x55, 0x9c, 0x2b, 0x0a, 0x55, 0xd6, 0xc8, 0x27, 0x18, 0x3f, 0x38, 0xcc, 0xc5, 0x1e, 0x44,
	0x19, 0x7e, 0x24, 0xc3, 0xd3, 0xe1, 0xf9, 0x96, 0xf6, 0x47, 0xb1, 0x0f, 0x1b, 0xcd, 0x74, 0x59,
	0x63, 0x32, 0xa2, 0xb7, 0x6d, 0xdd, 0x5e, 0xc4, 0x09, 0x00, 0xbe, 0x17, 0xa6, 0x9c, 0x3a, 0x63,
	0x57, 0x49, 0x44, 0x51, 0xa4, 0x7b, 0x2f, 0x92, 0xf2, 0x7b, 0x74, 0x1a, 0xdf, 0x6a, 0xac, 0xdc,
	0x3a, 0x55, 0xde, 0x40, 0xcc, 0x79, 0x55, 0xd8, 0x55, 0x85, 0xe2, 0x02, 0xc6, 0x86, 0xc6, 0x73,
	0x45, 0x3c, 0x39, 0x50, 0xbf, 0xf4, 0x94, 0x77, 0xd3, 0x5c, 0x22, 0xaf, 0x01, 0x9e, 0xeb, 0x1f,
	0xf2, 0x3f, 0x1a, 0x77, 0x20, 0xe6, 0xc6, 0x76, 0xa4, 0x37, 0xbc, 0xc3, 0xe5, 0xdf, 0x86, 0x54,
	0xce, 0x79, 0x5b, 0x3e, 0xf9, 0x1c, 0xc2, 0xe8, 0xf1, 0x45, 0xdc, 0x42, 0x44, 0xde, 0xe2, 0x68,
	0x6d, 0x50, 0xb7, 0xed, 0xe1, 0x71, 0x38, 0xfc, 0x9e, 0x3b, 0xf0, 0x0c, 0x12, 0x09, 0x30, 0xba,
	0xbd, 0x02, 0x8c, 0xbe, 0x3b, 0x33, 0xc8, 0x2e, 0xc0, 0xe8, 0x76, 0x0a, 0x30, 0x7a, 0x0b, 0xc9,
	0xc1, 0x6c, 0x93, 0xff, 0xc2, 0xd5, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x91, 0x9e, 0x6a,
	0x35, 0x02, 0x00, 0x00,
}
